### ISSUE TITLE
Need to implement groupBy function 

### ISSUE THREAD

**Issue by boussadjra** [MenaiAla/arrow#10]
Need to implement a function that looks like the sql `group by` statement in which we indicate the field to group by it and an aggregate function such as `sum`, `avg`, `count`, `min` and `max` , lets suppose that we have the following array : 

```js
let scores=[
  {
    "date": "2020-08-04",
    "time": "8:32",
    "score": 2
  },
  {
    "date": "2020-08-04",
    "time": "8:45",
    "score": 1
  },
  {
    "date": "2020-08-04",
    "time": "11:15",
    "score": 4
  },
  {
    "date": "2020-08-06",
    "time": "9:52",
    "score": 7
  },
  {
    "date": "2020-08-06",
    "time": "15:42",
    "score": 3
  },
  {
    "date": "2020-08-09",
    "time": "8:57",
    "score": 1
  },
  {
    "date": "2020-08-09",
    "time": "18:26",
    "score": 5
  }
]
``` 

expected result after applying the function `groupBy('date','sum','score')` : 

```
 [
    {
        date:'2020-08-04',
        score :7
    },
    {
        date:'2020-08-06',
        score:10
    },
    {
        date:'2020-08-09',
        score:6
    }]

```

or the other result by applying `groupBy('date','count','score')` or ` groupBy('date','count','*')` : 

````
 [
    {
        date:'2020-08-04',
        count:3
    },
    {
        date:'2020-08-06',
        count:2
    },
    {
        date:'2020-08-09',
        count:2
    }]
````

**Comment by MenaiAla** [comment]
I'm not sure will align with the library roadmap, I guess there's a similar one on @lodash.

**Comment by MenaiAla** [comment]
Let's first fix the CD/CI and creating stable TDD flow before adding more features.

**Comment by boussadjra** [comment]
I'm not very familiar with github actions and the CD/CI process, this the occasion to learn them.
