### ISSUE TITLE
How to export module to one index.js file ?

### ISSUE THREAD

**Issue by MenaiAla** [MenaiAla/arrow#13]
@boussadjra , I'm struggling to export the modules to one global file `index.js` then create a build setup from it.

please check [create-build-setup-branch](https://github.com/MenaiAla/arrow/tree/create-build-setup) and see how I created index.js for each folder ( has, math..) then create one index.js that import module from these indexes then run `npm run build` to build the setup.

The problem is I could not import the functions when I want to use the module for production.

**Comment by MenaiAla** [comment]
@boussadjra , would you take a look, please?

**Comment by boussadjra** [comment]
Sorry , I did not pay attention because there were a lot of notifications that talk about security updates in my different repositories. i  will try it out when i have enough time.

**Comment by MenaiAla** [comment]
@boussadjra , Thank you buddy, I appreciate your efforts.

**Comment by MenaiAla** [comment]
@boussadjra , fixed the issue [here](https://github.com/MenaiAla/arrow/tree/create-webpack-bundle).
