### ISSUE TITLE
Need average function implementation

### ISSUE THREAD

**Issue by MenaiAla** [MenaiAla/arrow#6]
[average.js](https://github.com/MenaiAla/arrow/blob/09fa08ca68ce83e7b373d57f2d0b51851bd2596f/src/1.x.x/scripts/array/math/average.js) is a module that contains a functions for calculating the average value of an array.

More details are comments on the [average.js](https://github.com/MenaiAla/arrow/blob/09fa08ca68ce83e7b373d57f2d0b51851bd2596f/src/1.x.x/scripts/array/math/average.js)
file.

**Comment by boussadjra** [comment]
I found in `averages.pec.js` file that you did : 

```js
 it("should return negative value for negative elements", () => {
        expect(average([-1, -2, -3])).toStrictEqual((-1 + (-2) + (-2)) / 3);
    });
```

the array items in the left side are not the same in the right side, is it a typo?

**Comment by larbibaraka** [comment]
@MenaiAla  i'm very sry i cant implement this i have some work to do

**Comment by boussadjra** [comment]
@larbibaraka i'm working on it, i have to pass two tests and it will be done

**Comment by MenaiAla** [comment]
@boussadjra , sorry for the late message I had some issue with my Internet, yes, I fixed it. Thank you.

**Comment by MenaiAla** [comment]
@larbibaraka , sorry to assign you without inform you .

**Comment by MenaiAla** [comment]
@boussadjra , please just follow the COMMITS_TEMPLATE rules for the better convention.

**Comment by boussadjra** [comment]
@MenaiAla please let know what i did wrong in order to avoid that the next time

**Comment by MenaiAla** [comment]
@boussadjra , Sorry I commented before I see your commit, in fact you understand the convention no worries.
