### ISSUE TITLE
Import functions directly or wrap them inside a module ?

### ISSUE THREAD

**Issue by MenaiAla** [MenaiAla/arrow#9]
@boussadjra , I need your opinion about exporting each function like in the example provided in README.

Or export an Object that lets the developers call the functions inside it.

In React we have the two options :

```
import React from "react"
React.createElement()
```
and

```
import {useEffect} from "react"
const effect = useEffect();
```

JS has a functional and OOP ( recently ) paradigm so I could get exactly the decision behind each architecture.

In Java, I was doing this by defining the static functions, factory functions, and instantiated functions... The concept was clean but JS behavior confuses me.

What's your opinion?

**Comment by boussadjra** [comment]
I think the best way is to give the developer  two choices, you give it a global object like `_` of lodash then he will use it `_.sum(array)` or he could also import each function between curly brackets like `import {sum} from 'arrow'`, i see that the most modern js libraries do that.

**Comment by MenaiAla** [comment]
What's your opinion about exporting a global variable `Arrow` like `React` that contains all modules.

Or should each `feature` ( folder of modules ) be a global object such as `Has`, `Math`..

**Comment by boussadjra** [comment]
I suggest to to export both a global variable `Arrow` and give the developer the possibility to import each function like we do with react hooks , the syntax should be like `import Array, {sum,multiply, has}` from 'arrow', the function names should be written in camel case format.
